# Common properties
server.port=8081
mybatis.configuration.map-underscore-to-camel-case=true

# Active profile: switch to 'prod' for formal environment
spring.profiles.active=dev

# Increase max upload size
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
