ALTER TABLE user ADD COLUMN IF NOT EXISTS address VARCHAR(255) DEFAULT NULL;
ALTER TABLE user ADD COLUMN IF NOT EXISTS wechat_id VARCHAR(50) DEFAULT NULL;
ALTER TABLE user ADD COLUMN IF NOT EXISTS age INT DEFAULT NULL;
ALTER TABLE user ADD COLUMN IF NOT EXISTS gender VARCHAR(10) DEFAULT 'OTHER';

