ALTER TABLE user ADD COLUMN address VARCHAR(255) DEFAULT NULL;
ALTER TABLE user ADD COLUMN wechat_id VARCHAR(50) DEFAULT NULL;
ALTER TABLE user ADD COLUMN age INT DEFAULT NULL;
ALTER TABLE user ADD COLUMN gender VARCHAR(10) DEFAULT 'OTHER';

